[package]
name = "luhn"
version = "1.0.2"
description = "A Luhn validation and checksum library"
authors = [
  "Jeff Carpenter <gcarpenterv@gmail.com>",
  "Alex Sayers <alex@asayers.com>",
]
license = "MIT"
edition = "2018"
repository = "https://github.com/jeffcarp/luhn-rs"
documentation = "https://docs.rs/luhn"
readme = "README.md"
keywords = ["luhn", "checksum", "credit-card", "validation", "isin"]
categories = ["algorithms", "cryptography"]

[dependencies]
digits_iterator = "0.1"
